"""Explainable generated/minified source heuristics."""

from pathlib import Path

_HEADERS = (
    "@generated",
    "auto-generated",
    "automatically generated",
    "do not edit",
    "generated by",
)


def generated_status(path: Path, text: str) -> tuple[str, list[str]]:
    reasons: list[str] = []
    head = text[:4096].lower()
    if any(marker in head for marker in _HEADERS):
        reasons.append("generated-header")
    lines = text.splitlines() or [text]
    if max(map(len, lines), default=0) > 2000:
        reasons.append("very-long-line")
    if path.name.endswith((".generated.ts", ".gen.ts", ".d.ts")):
        reasons.append("generated-filename")
    if len(lines) > 20 and len(set(lines)) / len(lines) < 0.25:
        reasons.append("high-repetition")
    return ("generated" if reasons else "human"), reasons
